### ISSUE TITLE
[Enhancement] Pre-fetch an image for Embedded Text and disable if there's an error

### ISSUE THREAD

**Issue by ntibbles** [ntibbles/equa11y#38]
In the "Embedded Text" utility, fetch the first image on the page and check if there's a CORS error. If so, disable the checkbox and add the text "(Not Available)".

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified the 'Embedded Text' utility to check for CORS errors on the first image, disable the checkbox, and add '(Not Available)' text if an error occurs.

You can review changes in this commit: https://github.com/mnmnk43434/ntibbles-equa11y-38/commit/d4388c3255c46a52a54e427371d72a7504f7be12.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
